import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faStar as faStarRegular,
    faSquare,
    faCheckSquare,
    faTrashAlt as faTrashRegular,
} from '@fortawesome/free-regular-svg-icons';
import {
    faFolderOpen,
    faUsers,
    faTasks,
    faBars,
    faStar,
    faClock,
    faPlus,
    faEdit,
    faTrashAlt,
    faCaretDown,
    faCaretRight,
    faCaretUp,
    faEllipsisH,
    faSignOutAlt,
    faTimes,
    faAngleLeft,
    faCheckSquare as CheckedSquare,
    faGripHorizontal,
    faChevronRight,
    faCheck,
    faPaperclip,
    faInbox,
    faCircle,
    faHome,
    faBell,
    faCheckDouble,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faFolderOpen,
    faUsers,
    faTasks,
    faBars,
    faStar,
    faClock,
    faPlus,
    faEdit,
    faTrashAlt,
    faCaretDown,
    faCaretRight,
    faCaretUp,
    faEllipsisH,
    faSignOutAlt,
    faTimes,
    faStarRegular,
    faAngleLeft,
    faSquare,
    faCheckSquare,
    CheckedSquare,
    faGripHorizontal,
    faChevronRight,
    faCheck,
    faPaperclip,
    faTrashRegular,
    faInbox,
    faCircle,
    faHome,
    faBell,
    faCheckDouble
);
